name: Publish release
on: create

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    if: |
      startsWith(github.ref, 'refs/tags/v') &&
      github.actor == '{{cookiecutter.github_username}}'

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Create release for tag
        run: |
          TAG=$(echo "$REF" | cut -c 11-)
          gh release create --verify-tag --generate-notes "$TAG"
        env:
          GITHUB_TOKEN: "{% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}"
          REF: "{% raw %}${{ github.ref }}{% endraw %}"
